### ISSUE TITLE
res rather than asset

### ISSUE THREAD

**Issue by Jam155** [mklimek/ssl-utils-android#2]
I'm just wondering wouldn't it make more sense for the certificate to be stored in the resources directory? I'm imagining res/raw or similar but this would seem to make more sense to me than storing it as an asset, then you could just refer to the file by its id?

Could you let me know if there's a reason this currently isn't the case? Thanks.

**Comment by mklimek** [comment]
When I wrote this lib I used it in a project where assets were organized in not a flat file structure (which is not supported by res/raw). Not any other particular reason other than that :)
